### ISSUE TITLE
Modification of cli parameters

### ISSUE THREAD

**Issue by zveinn** [zveinn/dplz#4]
# Remove project concept
# Remove deployment concept
# Add/Change --servers/-s cli input and --variables/-v 
```
$ dplz -s server1.json server2.json server3.json ...
$ dplz -s *server.json (PRERFIX)
$ dplz -s server_*.json (WILDCARD)
$ dplz -s x/*_server_*.json 
```

**Comment by LohanGuedes** [comment]
I'd like to start working on this issue.

I'll come back with updates.

**Comment by LohanGuedes** [comment]
Issue should be closed:
Link #10
